#!/usr/bin/env perl

use strict;
use warnings;

use MongoDB;
use boolean;

my $db = MongoDB::MongoClient->new->get_database('users');
$db->get_collection('user')->drop;
$db->get_collection('user')->ensure_index({login => 1}, {unique => true});
